In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
USAhousing = pd.read_csv('USA_Housing.csv')
X = USAhousing[['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms','Avg. Area Number of Bedrooms', 'Area Population']]
y = USAhousing['Price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state= 1)

In [3]:
USAhousing.head(40)

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Address,Price
0,79545.45857,5.682861,7.009188,4.09,23086.80050,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701...",1.059034e+06
1,79248.64245,6.002900,6.730821,3.09,40173.07217,"188 Johnson Views Suite 079\nLake Kathleen, CA...",1.505891e+06
2,61287.06718,5.865890,8.512727,5.13,36882.15940,"9127 Elizabeth Stravenue\nDanieltown, WI 06482...",1.058988e+06
3,63345.24005,7.188236,5.586729,3.26,34310.24283,USS Barnett\nFPO AP 44820,1.260617e+06
4,59982.19723,5.040555,7.839388,4.23,26354.10947,USNS Raymond\nFPO AE 09386,6.309435e+05
5,80175.75416,4.988408,6.104512,4.04,26748.42842,"06039 Jennifer Islands Apt. 443\nTracyport, KS...",1.068138e+06
6,64698.46343,6.025336,8.147760,3.41,60828.24909,"4759 Daniel Shoals Suite 442\nNguyenburgh, CO ...",1.502056e+06
7,78394.33928,6.989780,6.620478,2.42,36516.35897,"972 Joyce Viaduct\nLake William, TN 17778-6483",1.573937e+06
8,59927.66081,5.362126,6.393121,2.30,29387.39600,USS Gilbert\nFPO AA 20957,7.988695e+05
9,81885.92718,4.423672,8.167688,6.10,40149.96575,Unit 9446 Box 0958\nDPO AE 97025,1.545155e+06
10,80527.47208,8.093513,5.042747,4.10,47224.35984,"6368 John Motorway Suite 700\nJanetbury, NM 26854",1.707046e+06
11,50593.69550,4.496513,7.467627,4.49,34343.99189,"911 Castillo Park Apt. 717\nDavisborough, PW 7...",6.637324e+05
12,39033.80924,7.671755,7.250029,3.10,39220.36147,"209 Natasha Stream Suite 961\nHuffmanland, NE ...",1.042814e+06
13,73163.66344,6.919535,5.993188,2.27,32326.12314,"829 Welch Track Apt. 992\nNorth John, AR 26532...",1.291332e+06
14,69391.38018,5.344776,8.406418,4.37,35521.29403,"PSC 5330, Box 4420\nAPO AP 08302",1.402818e+06
15,73091.86675,5.443156,8.517513,4.01,23929.52405,"2278 Shannon View\nNorth Carriemouth, NM 84617",1.306675e+06
16,79706.96306,5.067890,8.219771,3.12,39717.81358,"064 Hayley Unions\nNicholsborough, HI 44161-1887",1.556787e+06
17,61929.07702,4.788550,5.097010,4.30,24595.90150,"5498 Rachel Locks\nNew Gregoryshire, PW 54755",5.284852e+05
18,63508.19430,5.947165,7.187774,5.12,35719.65305,Unit 7424 Box 2786\nDPO AE 71255,1.019426e+06
19,62085.27640,5.739411,7.091808,5.49,44922.10670,"19696 Benjamin Cape\nStephentown, ME 36952-4733",1.030591e+06
20,86294.99909,6.627457,8.011898,4.07,47560.77534,"030 Larry Park Suite 665\nThomashaven, HI 8794...",2.146925e+06
21,60835.08998,5.551222,6.517175,2.10,45574.74166,USNS Brown\nFPO AP 85833,9.292476e+05
22,64490.65027,4.210323,5.478088,4.31,40358.96011,"95198 Ortiz Key\nPort Sara, TN 24541-2855",7.188872e+05
23,60697.35154,6.170484,7.150537,6.34,28140.96709,"9003 Jay Plains Suite 838\nLake Elizabeth, IN ...",7.439998e+05
24,59748.85549,5.339340,7.748682,4.23,27809.98654,"24282 Paul Valley\nWest Perry, MI 03169-5806",8.957371e+05
25,56974.47654,8.287562,7.312880,4.33,40694.86951,"61938 Brady Falls\nLewisfort, DE 61227",1.453975e+06
26,82173.62608,4.018525,6.992699,2.03,38853.91807,"3599 Ramirez Springs\nJacksonhaven, AZ 72798",1.125693e+06
27,64626.88098,5.443360,6.988754,4.00,27784.74228,"073 Christopher Falls Suite 882\nWest Cynthia,...",9.754295e+05
28,90499.05745,6.384359,4.242191,3.04,33970.16499,"6531 Chase Prairie Apt. 245\nSusanshire, MN 22365",1.240764e+06
29,59323.79210,6.977828,8.273697,4.07,37520.65773,"17124 Johnson Squares\nLake Robertfurt, AL 618...",1.577018e+06
30,77811.52203,5.314460,6.686686,3.24,33754.73780,"1359 Mitchell Vista\nCourtneyfort, NY 93065-7224",1.246830e+06
31,68652.60921,6.124342,6.290820,4.42,39355.62573,"4343 Joshua Lake Suite 096\nPierceview, NV 626...",1.170721e+06
32,55041.35158,7.127129,8.591923,5.36,30122.47348,"0057 Jacob Coves Apt. 932\nLake Emily, VA 3946...",1.071279e+06
33,50218.70846,6.118808,7.333554,6.29,16810.78331,"039 Jordan Pike\nEmilyville, ID 27442",5.343051e+05
34,55909.32230,5.419563,9.289854,6.00,22355.23541,"66338 Novak Curve Suite 628\nTaylorborough, OK...",9.363690e+05
35,74372.81021,5.500129,6.593046,2.07,39395.15118,"7167 Angela Park Suite 013\nMorrishaven, NH 66...",1.199194e+06
36,78667.90460,5.470652,7.780837,4.10,27637.65655,"34964 Sara Fields Apt. 584\nPort Raymondville,...",1.233220e+06
37,78699.51510,5.652784,6.756454,3.01,22836.60757,"7585 Lynn Loop\nEast Judy, WV 73336",1.081150e+06
38,53128.18545,5.180664,5.426903,2.39,32947.71196,Unit 1388 Box 9350\nDPO AP 70848,5.247128e+05
39,17796.63119,4.949557,6.713905,2.50,47162.18364,"9932 Eric Circles\nLake Martha, WY 34611-6127",3.023558e+05

In [4]:
USAhousing.describe() #all statistical information

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5.000000e+03
mean,68583.108984,5.977222,6.987792,3.981330,36163.516039,1.232073e+06
std,10657.991214,0.991456,1.005833,1.234137,9925.650114,3.531176e+05
min,17796.631190,2.644304,3.236194,2.000000,172.610686,1.593866e+04
25%,61480.562390,5.322283,6.299250,3.140000,29403.928700,9.975771e+05
50%,68804.286405,5.970429,7.002902,4.050000,36199.406690,1.232669e+06
75%,75783.338665,6.650808,7.665871,4.490000,42861.290770,1.471210e+06
max,107701.748400,9.519088,10.759588,6.500000,69621.713380,2.469066e+06

In [5]:
lm = LinearRegression()
lm= lm.fit(X_train,y_train)
predictions = lm.predict(X_test)
accuracy = lm.score(X_test,y_test)
print(accuracy*100,'%')

92.15935236979011 %